
services:
  php:
    build: ./docker/php
    container_name: mmikhailov-symfony-php
    working_dir: /var/www/symfony
    volumes:
      - ./:/var/www/symfony
    environment:
      - DATABASE_URL=mysql://symfony_test:symfony@mmikhailov-mariadb:3306/symfony_test
    command: >
      sh -c "composer install && bin/console doctrine:mig:mig --no-interaction && php-fpm"
    depends_on:
      db:
        condition: service_healthy

  nginx:
    image: nginx:latest
    container_name: mmikhailov-symfony-nginx
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/symfony
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  vue:
    image: node:23-alpine
    container_name: mmikhailov-vue-app
    working_dir: /app
    volumes:
      - ./:/app
    command: npm install && npm run build

  db:
    image: mariadb:11.4
    container_name: mmikhailov-mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=toor
      - MARIADB_DATABASE=symfony_test
      - MARIADB_USER=symfony_test
      - MARIADB_PASSWORD=symfony
    healthcheck:
      test: ["CMD-SHELL", "mariadb -h 127.0.0.1 -u $$MARIADB_USER -p$$MARIADB_PASSWORD -e 'select 1'"]
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - "3306:3306"
    volumes:
      - mmikhailov-db-data:/var/lib/mysql

volumes:
  mmikhailov-db-data:
